"""Setting definitions for the notes service."""

from platform_settings import SettingDef, SettingType

DEFS = [
    SettingDef(
        key="notes.sort.default",
        module="notes",
        type=SettingType.CHOICE,
        default="updated",
        choices=("updated", "created", "title"),
        description="Default note sort order",
    ),
    SettingDef(
        key="notes.list.page_size",
        module="notes",
        type=SettingType.INT,
        default=100,
        min=10,
        max=500,
        description="Default list page size",
    ),
    SettingDef(
        key="notes.editor.autosave_s",
        module="notes",
        type=SettingType.INT,
        default=5,
        min=0,
        max=120,
        description="Editor autosave interval (seconds; 0=off)",
    ),
    SettingDef(
        key="notes.trash.retention_days",
        module="notes",
        type=SettingType.INT,
        default=30,
        min=0,
        max=365,
        description="Trash retention days (0=keep forever; purged automatically after expiry)",
    ),
    SettingDef(
        key="notes.history.per_note",
        module="notes",
        type=SettingType.INT,
        default=20,
        min=0,
        max=100,
        description="History versions kept per note (0=disable version history)",
    ),
    SettingDef(
        key="notes.export.dir",
        module="notes",
        type=SettingType.STR,
        default="workspace/notes-export",
        description="Directory for exported Markdown files",
    ),
    SettingDef(
        key="notes.assets.max_mb",
        module="notes",
        type=SettingType.INT,
        default=20,
        min=1,
        max=100,
        description="Max size per image attachment (MB)",
    ),
    # Notes-page-only UI preference; separate from the site-wide
    # appearance.font_scale. User buttons and agents have equal access.
    SettingDef(
        key="notes.ui.font_size",
        module="notes",
        type=SettingType.INT,
        default=15,
        min=12,
        max=24,
        description="Note content font size (px; notes page only, does not affect the whole site)",
    ),
    SettingDef(
        key="notes.ui.mode",
        module="notes",
        type=SettingType.CHOICE,
        default="edit",
        choices=("edit", "preview", "split"),
        description="Notes workspace view: edit / preview / split",
    ),
    SettingDef(
        key="notes.ui.layout",
        module="notes",
        type=SettingType.CHOICE,
        default="list",
        choices=("list", "card"),
        description="Notes home layout: list or card",
    ),
    SettingDef(
        key="notes.ui.sync_scroll",
        module="notes",
        type=SettingType.BOOL,
        default=True,
        description="Sync scroll between editor and preview in split mode",
    ),
    SettingDef(
        key="notes.ui.list_state",
        module="notes",
        type=SettingType.CHOICE,
        default="active",
        choices=("active", "archived"),
        description="Notes home shows active or archived",
    ),
    SettingDef(
        key="notes.ui.sort",
        module="notes",
        type=SettingType.CHOICE,
        default="updated",
        choices=("updated", "created", "title"),
        description="Notes home sort: recently updated/recently created/title",
    ),
    SettingDef(
        key="notes.ui.filter",
        module="notes",
        type=SettingType.CHOICE,
        default="all",
        choices=("all", "pinned", "untitled", "unlinked", "today"),
        description="Notes home filter: all/pinned/untitled/unlinked/today",
    ),
    SettingDef(
        key="notes.ui.query",
        module="notes",
        type=SettingType.STR,
        default="",
        description="Notes home keyword (title or excerpt)",
    ),
    SettingDef(
        key="notes.ui.source_id",
        module="notes",
        type=SettingType.STR,
        default="",
        description="Notes home filter by linked source (empty=all)",
    ),
    SettingDef(
        key="notes.ui.panel",
        module="notes",
        type=SettingType.CHOICE,
        default="none",
        choices=("none", "trash"),
        description="Panel open on the notes page: none/trash",
    ),
    SettingDef(
        key="notes.ui.density",
        module="notes",
        type=SettingType.CHOICE,
        default="comfortable",
        choices=("comfortable", "compact"),
        description="Notes home list density",
    ),
    SettingDef(
        key="notes.ui.toc_width",
        module="notes",
        type=SettingType.INT,
        default=188,
        min=148,
        max=480,
        description="Notes workspace TOC width (px)",
    ),
]
