"""Generate the package-level dependency graph (mermaid) from the same
root packages import-linter checks, so the diagram can never disagree with
the enforced contracts.

Usage:
    python scripts/gen_dep_graph.py          # write the docs/catalog/module-graph.* pair
    python scripts/gen_dep_graph.py --check  # exit 1 when a file is missing or stale

The output is the committed bilingual docs pair plus its consistency record:
`docs/catalog/module-graph.md`, `module-graph.zh.md`, `module-graph.i18n.yaml`
(the pairing contract is docs/i18n/README.md).

Edges are direct imports aggregated to the top-level package (one arrow per
importer -> imported pair, sorted for a deterministic diff). Single
responsibility: graph generation; layering rules stay in import-linter.ini.
"""

from __future__ import annotations

import configparser
import hashlib
import sys
from pathlib import Path

import grimp

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "import-linter.ini"
OUT_DIR = ROOT / "docs" / "catalog"
OUT_EN = OUT_DIR / "module-graph.md"
OUT_ZH = OUT_DIR / "module-graph.zh.md"
OUT_I18N = OUT_DIR / "module-graph.i18n.yaml"

#: Visual grouping of root packages (mermaid subgraphs); packages missing
#: from the map fall into "domains".
LAYERS: dict[str, tuple[str, ...]] = {
    "harness": ("agent",),
    "runtime": ("host", "gateway"),
    "platform": (
        "platform_actor",
        "platform_capability",
        "platform_contracts",
        "platform_eventbus",
        "platform_health",
        "platform_secrets",
        "platform_settings",
        "platform_webguard",
    ),
}


def root_packages() -> list[str]:
    parser = configparser.ConfigParser()
    parser.read(CONFIG, encoding="utf-8")
    raw = parser.get("importlinter", "root_packages")
    return [line.strip() for line in raw.splitlines() if line.strip()]


def package_edges(packages: list[str]) -> set[tuple[str, str]]:
    graph = grimp.build_graph(*packages, include_external_packages=False)
    edges: set[tuple[str, str]] = set()
    for module in graph.modules:
        importer = module.split(".", 1)[0]
        for imported in graph.find_modules_directly_imported_by(module):
            target = imported.split(".", 1)[0]
            if importer != target:
                edges.add((importer, target))
    return edges


def render_body(packages: list[str], edges: set[tuple[str, str]]) -> list[str]:
    grouped: dict[str, list[str]] = {name: [] for name in LAYERS}
    grouped["domains"] = []
    for pkg in packages:
        layer = next((name for name, members in LAYERS.items() if pkg in members), "domains")
        grouped[layer].append(pkg)
    lines = [
        "```mermaid",
        "graph LR",
    ]
    for layer, members in grouped.items():
        if not members:
            continue
        lines.append(f"    subgraph {layer}")
        # Node ids are prefixed: bare package names such as `graph` collide
        # with mermaid keywords.
        lines.extend(f'        p_{pkg}["{pkg}"]' for pkg in sorted(members))
        lines.append("    end")
    lines.extend(f"    p_{src} --> p_{dst}" for src, dst in sorted(edges))
    lines.append("```")
    return lines


NOTE_EN = (
    "Generated by `scripts/gen_dep_graph.py` from the `root_packages` of",
    "`import-linter.ini` (direct imports aggregated per top-level package).",
    "Do not edit by hand; run `npm run graph` after changing imports.",
)
NOTE_ZH = (
    "由 `scripts/gen_dep_graph.py` 依 `import-linter.ini` 所声明的 `root_packages` 生成",
    "(按顶层包聚合直接 import)。请勿手改;变更 import 后运行 `npm run graph`。",
)


def render_en(packages: list[str], edges: set[tuple[str, str]]) -> str:
    lines = [
        "# Module dependency graph",
        "",
        "English | [中文](module-graph.zh.md)",
        "",
        *NOTE_EN,
        "",
    ]
    lines.extend(render_body(packages, edges))
    lines.append("")
    return "\n".join(lines)


def render_zh(packages: list[str], edges: set[tuple[str, str]]) -> str:
    lines = ["# 模块依赖图", "", "[English](module-graph.md) | 中文", "", *NOTE_ZH, ""]
    lines.extend(render_body(packages, edges))
    lines.append("")
    return "\n".join(lines)


def blob_hash(text: str) -> str:
    """The hash `git hash-object` records for this content (blob <len>\\0<body>)."""
    data = text.encode("utf-8")
    return hashlib.sha1(b"blob %d\0" % len(data) + data).hexdigest()


def render_i18n(en: str, zh: str) -> str:
    return "\n".join(
        [
            "# Bilingual-pair consistency record (docs/catalog/module-graph.md): the git blob",
            "# hash of each side as of the last confirmed-consistent state. Both languages",
            "# carry equal authority; this file is regenerated by scripts/gen_dep_graph.py.",
            f"docs/catalog/module-graph.md: {blob_hash(en)}",
            f"docs/catalog/module-graph.zh.md: {blob_hash(zh)}",
            "",
        ]
    )


def main(argv: list[str]) -> int:
    check = "--check" in argv
    packages = root_packages()
    edges = package_edges(packages)
    files = {
        OUT_EN: render_en(packages, edges),
        OUT_ZH: render_zh(packages, edges),
    }
    files[OUT_I18N] = render_i18n(files[OUT_EN], files[OUT_ZH])
    if check:
        for path, text in files.items():
            if not path.exists():
                print(f"missing {path.relative_to(ROOT)}: run `npm run graph`", file=sys.stderr)
                return 1
            if path.read_text(encoding="utf-8") != text:
                print(f"stale {path.relative_to(ROOT)}: run `npm run graph`", file=sys.stderr)
                return 1
        print("dependency graph is fresh")
        return 0
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for path, text in files.items():
        path.write_text(text, encoding="utf-8")
    print(f"wrote {OUT_EN.relative_to(ROOT)} ({len(packages)} packages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
