"""Generate the package-level dependency graph (mermaid) from the same
root packages import-linter checks, so the diagram can never disagree with
the enforced contracts.

Usage:
    python scripts/gen_dep_graph.py          # write docs-local/arch-diagrams/module-graph.md
    python scripts/gen_dep_graph.py --check  # exit 1 when the file is missing or stale

Edges are direct imports aggregated to the top-level package (one arrow per
importer -> imported pair, sorted for a deterministic diff). Single
responsibility: graph generation; layering rules stay in import-linter.ini.
"""

from __future__ import annotations

import configparser
import sys
from pathlib import Path

import grimp

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "import-linter.ini"
OUTPUT = ROOT / "docs-local" / "arch-diagrams" / "module-graph.md"

#: Visual grouping of root packages (mermaid subgraphs); packages missing
#: from the map fall into "domains".
LAYERS: dict[str, tuple[str, ...]] = {
    "harness": ("agent",),
    "runtime": ("host", "gateway"),
    "platform": (
        "platform_actor",
        "platform_capability",
        "platform_contracts",
        "platform_eventbus",
        "platform_health",
        "platform_secrets",
        "platform_settings",
        "platform_webguard",
    ),
}


def root_packages() -> list[str]:
    parser = configparser.ConfigParser()
    parser.read(CONFIG, encoding="utf-8")
    raw = parser.get("importlinter", "root_packages")
    return [line.strip() for line in raw.splitlines() if line.strip()]


def package_edges(packages: list[str]) -> set[tuple[str, str]]:
    graph = grimp.build_graph(*packages, include_external_packages=False)
    edges: set[tuple[str, str]] = set()
    for module in graph.modules:
        importer = module.split(".", 1)[0]
        for imported in graph.find_modules_directly_imported_by(module):
            target = imported.split(".", 1)[0]
            if importer != target:
                edges.add((importer, target))
    return edges


def render(packages: list[str], edges: set[tuple[str, str]]) -> str:
    grouped: dict[str, list[str]] = {name: [] for name in LAYERS}
    grouped["domains"] = []
    for pkg in packages:
        layer = next((name for name, members in LAYERS.items() if pkg in members), "domains")
        grouped[layer].append(pkg)
    lines = [
        "# Module dependency graph",
        "",
        "Generated by `scripts/gen_dep_graph.py` from the `root_packages` of",
        "`import-linter.ini` (direct imports aggregated per top-level package).",
        "Do not edit by hand; run `npm run graph` after changing imports.",
        "",
        "```mermaid",
        "graph LR",
    ]
    for layer, members in grouped.items():
        if not members:
            continue
        lines.append(f"    subgraph {layer}")
        # Node ids are prefixed: bare package names such as `graph` collide
        # with mermaid keywords.
        lines.extend(f'        p_{pkg}["{pkg}"]' for pkg in sorted(members))
        lines.append("    end")
    lines.extend(f"    p_{src} --> p_{dst}" for src, dst in sorted(edges))
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    check = "--check" in argv
    packages = root_packages()
    text = render(packages, package_edges(packages))
    if check:
        if not OUTPUT.exists():
            print(f"missing {OUTPUT.relative_to(ROOT)}: run `npm run graph`", file=sys.stderr)
            return 1
        if OUTPUT.read_text(encoding="utf-8") != text:
            print(f"stale {OUTPUT.relative_to(ROOT)}: run `npm run graph`", file=sys.stderr)
            return 1
        print("dependency graph is fresh")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(packages)} packages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
